[package]
name = "singleflight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
crossbeam = "0.8.2"
crossbeam-utils = "0.8"
hashbrown = "0.12"
parking_lot = "0.12"